---
- hosts: webservers
  sudo: yes
  vars:
    http_port: 80
    http_host: localhost
    doc_dir: /ansible/
    doc_root: /var/www/html/
    max-clients: 5
    http_conf: localhoost.conf

  vars_prompt:
    - name: username
      prompt: What is your name? 

  tasks:
  - name: Ensure that Apache is installed
    apt: name=apache2 state=present
    when : ansible_os_family == "Debian"

  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started

  - name: Deploy configuration file
    template: src=templates/httpd.j2 dest=/etc/apache2/sites-available/{{ http_conf }}
    notify:
      - Restart Apache

  - name: Copy Site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html
    
  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted

  
- hosts: dbservers
  sudo: yes

  tasks: 
  - name: Ensure MySQL is installed
    apt: name=mysql-server state=present
    when : ansible_os_family == "Debian"

  - name: Start MySQL
    service: name=mysql state=started

